"use client";

import { Inter } from "next/font/google";
import "./globals.css";
<<<<<<< HEAD
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import { usePathname } from "next/navigation";
=======
import { AuthProvider } from "./contexts/AuthConext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
>>>>>>> 1e3f8c13da9ce1eb0833fdfc833ca2a3b08401eb

export default function RootLayout({ children }) {
  const pathname = usePathname();
  return (
    <html lang="en">
<<<<<<< HEAD
      <body>
        {pathname !== "/login" && pathname !== "/Signup" ? (
          <div className="bg-white ">
            <Navbar />
            <main className="bg-white  mx-auto">{children}</main>
            <Footer />
          </div>
        ) : (
          <main className="bg-white  mx-auto">{children}</main>
        )}
      </body>
=======
      <AuthProvider>

      <body className={inter.className}>{children}</body>
      </AuthProvider>
>>>>>>> 1e3f8c13da9ce1eb0833fdfc833ca2a3b08401eb
    </html>
  );
}
